### PR TITLE
Email Verification Feature Added

### PR DESCRIPTION
**Pull request by lazycipher**
This PR solves issue #10!
I've added the following things-
1. Token Model
2. `isVerified` property in the User model
3. Verified Users can only log in.
4. On Registration, the user gets a verification email
5. `GET` on `/api/verification/:token` checks the validity of the token. If correct then sends `verification.html` to the user for entering the verification code sent on email.
6. `PATCH` on `/api/verification` checks and modifies the user document's `isVerified` property.
7.  `POST` on `/api/verification/resend` re-sends the verification email to the user.

### CODE REVIEW

**Comment by lazycipher** [comment]
@honeycoder96, Please review this PR.

**Comment by honeycoder96** [comment]
hi @lazycipher , did u implement these routes on frontend?

**Comment by lazycipher** [comment]
@honeycoder96, I haven't done anything with technojam-frontend.
I've implemented things such that once a user signs up, he receives an email from our side with verification code. Now, the user will have to enter the verification code in a form to get it verified.
All these things are handled or served from the backend only!

**Comment by lazycipher** [comment]
@honeycoder96, I've changed the code to take `mailer` details from user environment variables.
Please look into this PR.

**Pull request merged**
